# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Discord and Cloudinary credentials (replace with your values)
DISCORD_CLIENT_ID=your_discord_client_id
CLOUDINARY_CLOUD_NAME=your_cloud_name
